<?php

/**
 * This is the model base class for the table "{{OrderFlow}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderFlow".
 *
 * Columns in table "{{OrderFlow}}" available as properties of the model,
 * followed by relations of table "{{OrderFlow}}" available as properties of the model.
 *
 * @property integer $srcID
 * @property integer $dstID
 * @property integer $priority
 *
 * @property OrderStatus $dst
 * @property OrderStatus $src
 */
abstract class BaseOrderFlow extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{OrderFlow}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderFlow|OrderFlows', $n);
	}

	public static function representingColumn() {
		return array(
			'srcID',
			'dstID',
		);
	}

	public function rules() {
		return array(
			array('srcID, dstID, priority', 'numerical', 'integerOnly'=>true),
			array('srcID, dstID, priority', 'default', 'setOnEmpty' => true, 'value' => null),
			array('srcID, dstID, priority', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'dst' => array(self::BELONGS_TO, 'OrderStatus', 'dstID'),
			'src' => array(self::BELONGS_TO, 'OrderStatus', 'srcID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'srcID' => null,
			'dstID' => null,
			'priority' => Yii::t('app', 'Priority'),
			'dst' => null,
			'src' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('srcID', $this->srcID);
		$criteria->compare('dstID', $this->dstID);
		$criteria->compare('priority', $this->priority);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}