<?php

/**
 * This is the model base class for the table "{{UserBranchType}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserBranchType".
 *
 * Columns in table "{{UserBranchType}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $userID
 * @property integer $branchBranchTypeID
 *
 */
abstract class BaseUserBranchType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{UserBranchType}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserBranchType|UserBranchTypes', $n);
	}

	public static function representingColumn() {
		return array(
			'userID',
			'branchBranchTypeID',
		);
	}

	public function rules() {
		return array(
			array('userID, branchBranchTypeID', 'numerical', 'integerOnly'=>true),
			array('userID, branchBranchTypeID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('userID, branchBranchTypeID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'userID' => null,
			'branchBranchTypeID' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('userID', $this->userID);
		$criteria->compare('branchBranchTypeID', $this->branchBranchTypeID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}