<?php

/**
 * This is the model base class for the table "{{OrderStatus}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderStatus".
 *
 * Columns in table "{{OrderStatus}}" available as properties of the model,
 * followed by relations of table "{{OrderStatus}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $priority
 *
 * @property Order[] $orders
 * @property OrderAction[] $orderActions
 * @property OrderFlow[] $orderFlows
 * @property OrderFlow[] $orderFlows1
 */
abstract class BaseOrderStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{OrderStatus}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderStatus|OrderStatuses', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('priority', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>20),
			array('name, priority', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, priority', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'orders' => array(self::HAS_MANY, 'Order', 'orderStatusID'),
			'orderActions' => array(self::HAS_MANY, 'OrderAction', 'orderStatusID'),
			'orderFlows' => array(self::HAS_MANY, 'OrderFlow', 'dstID'),
			'orderFlows1' => array(self::HAS_MANY, 'OrderFlow', 'srcID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'priority' => Yii::t('app', 'Priority'),
			'orders' => null,
			'orderActions' => null,
			'orderFlows' => null,
			'orderFlows1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('priority', $this->priority);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}