<?php

/**
 * This is the model base class for the table "{{UserBranch}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserBranch".
 *
 * Columns in table "{{UserBranch}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $userID
 * @property integer $branchID
 *
 */
abstract class BaseUserBranch extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{UserBranch}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserBranch|UserBranches', $n);
	}

	public static function representingColumn() {
		return array(
			'userID',
			'branchID',
		);
	}

	public function rules() {
		return array(
			array('userID, branchID', 'numerical', 'integerOnly'=>true),
			array('userID, branchID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('userID, branchID', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'userID' => null,
			'branchID' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('userID', $this->userID);
		$criteria->compare('branchID', $this->branchID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}