<?php

/**
 * This is the model base class for the table "{{Api}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Api".
 *
 * Columns in table "{{Api}}" available as properties of the model,
 * followed by relations of table "{{Api}}" available as properties of the model.
 *
 * @property integer $branchID
 * @property string $token
 * @property string $authentication
 *
 * @property Branch $branch
 */
abstract class BaseApi extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{Api}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Api|Apis', $n);
	}

	public static function representingColumn() {
		return 'token';
	}

	public function rules() {
		return array(
			array('branchID', 'numerical', 'integerOnly'=>true),
			array('token, authentication', 'length', 'max'=>36),
			array('branchID, token, authentication', 'default', 'setOnEmpty' => true, 'value' => null),
			array('branchID, token, authentication', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'branch' => array(self::BELONGS_TO, 'Branch', 'branchID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'branchID' => null,
			'token' => Yii::t('app', 'Token'),
			'authentication' => Yii::t('app', 'Authentication'),
			'branch' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('branchID', $this->branchID);
		$criteria->compare('token', $this->token, true);
		$criteria->compare('authentication', $this->authentication, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}