<?php

/**
 * This is the model base class for the table "{{SupportType}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SupportType".
 *
 * Columns in table "{{SupportType}}" available as properties of the model,
 * followed by relations of table "{{SupportType}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $parentID
 * @property integer $priority
 *
 * @property Support[] $supports
 * @property SupportType $parent
 * @property SupportType[] $supportTypes
 */
abstract class BaseSupportType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{SupportType}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SupportType|SupportTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('parentID, priority', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>20),
			array('name, parentID, priority', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, parentID, priority', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'supports' => array(self::HAS_MANY, 'Support', 'supportTypeID'),
			'parent' => array(self::BELONGS_TO, 'SupportType', 'parentID'),
			'supportTypes' => array(self::HAS_MANY, 'SupportType', 'parentID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'parentID' => null,
			'priority' => Yii::t('app', 'Priority'),
			'supports' => null,
			'parent' => null,
			'supportTypes' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('parentID', $this->parentID);
		$criteria->compare('priority', $this->priority);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}