<?php

/**
 * This is the model base class for the table "{{BranchType}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BranchType".
 *
 * Columns in table "{{BranchType}}" available as properties of the model,
 * followed by relations of table "{{BranchType}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property integer $priority
 *
 * @property BranchBranchType[] $branchBranchTypes
 * @property Workflow[] $workflows
 * @property Workflow[] $workflows1
 */
abstract class BaseBranchType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{BranchType}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BranchType|BranchTypes', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('priority', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('name, priority', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, priority', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'branchBranchTypes' => array(self::HAS_MANY, 'BranchBranchType', 'branchTypeID'),
			'workflows' => array(self::HAS_MANY, 'Workflow', 'nextBranchTypeID'),
			'workflows1' => array(self::HAS_MANY, 'Workflow', 'branchTypeID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'priority' => Yii::t('app', 'Priority'),
			'branchBranchTypes' => null,
			'workflows' => null,
			'workflows1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('priority', $this->priority);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}